'use client';

import type { CoachingNotes, CoachingSource } from '@/types';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { cn } from '@/lib/utils';

function sourceLabel(source: CoachingSource | undefined): string | null {
  if (source === 'llm') return 'Generated by AI';
  if (source === 'rule') return 'Rule-based coach';
  return null;
}

function renderSummary(summary: string, compact: boolean) {
  const blocks = summary
    .split(/\n{2,}/)
    .map((block) => block.trim())
    .filter(Boolean);
  const visible = compact ? blocks.slice(0, 2) : blocks;

  return visible.map((block, index) => {
    const lines = block.split('\n').map((line) => line.trim()).filter(Boolean);
    const listed = lines.every((line) => /^(- |\* |\d+\. )/.test(line));
    if (listed) {
      return (
        <ul key={index} className="list-disc space-y-1 pl-5 text-sm text-zinc-300">
          {lines.map((line) => (
            <li key={line}>{line.replace(/^(- |\* |\d+\. )/, '')}</li>
          ))}
        </ul>
      );
    }
    return (
      <p key={index} className="text-sm leading-relaxed text-zinc-300">
        {block}
      </p>
    );
  });
}

export function CoachSourceBadge({ source }: { source?: CoachingSource }) {
  const label = sourceLabel(source);
  if (!label) return null;
  return (
    <Badge variant={source === 'llm' ? 'success' : 'default'} className="font-normal">
      {label}
    </Badge>
  );
}

export function AiCoachNotesSkeleton({ variant = 'full' }: { variant?: 'full' | 'preview' | 'compact' }) {
  return (
    <Card className={cn(variant === 'compact' && 'border-emerald-500/15 bg-emerald-500/5')}>
      <CardHeader className={variant === 'compact' ? 'p-4 pb-2' : undefined}>
        <CardDescription>AI Coach Notes</CardDescription>
        <div className="mt-2 h-4 w-2/3 animate-pulse rounded bg-white/10" />
      </CardHeader>
      <CardContent className={cn('space-y-2', variant === 'compact' && 'p-4 pt-0')}>
        <div className="h-3 w-full animate-pulse rounded bg-white/5" />
        <div className="h-3 w-5/6 animate-pulse rounded bg-white/5" />
        {variant === 'full' ? <div className="h-3 w-4/6 animate-pulse rounded bg-white/5" /> : null}
      </CardContent>
    </Card>
  );
}

interface AiCoachNotesProps {
  notes: CoachingNotes | null | undefined;
  loading?: boolean;
  variant?: 'full' | 'preview' | 'compact';
}

export function AiCoachNotes({ notes, loading = false, variant = 'full' }: AiCoachNotesProps) {
  if (loading && !notes?.summary) {
    return <AiCoachNotesSkeleton variant={variant} />;
  }
  if (!notes?.summary) return null;

  const preview = variant === 'preview';
  const compact = variant === 'compact';

  return (
    <Card className={cn(compact && 'border-emerald-500/20 bg-emerald-500/5')}>
      <CardHeader className={cn(compact && 'p-4 pb-2', preview && 'pb-3')}>
        <div className="flex flex-wrap items-center justify-between gap-2">
          <CardDescription>AI Coach Notes</CardDescription>
          <CoachSourceBadge source={notes.source} />
        </div>
        {notes.headline ? (
          <CardTitle className={cn(compact || preview ? 'text-base' : 'text-lg')}>
            {notes.headline}
          </CardTitle>
        ) : (
          <CardTitle className={cn(compact || preview ? 'text-base' : 'text-lg')}>
            Session coaching
          </CardTitle>
        )}
      </CardHeader>
      <CardContent className={cn('space-y-3', compact && 'p-4 pt-0', preview && 'pt-0')}>
        <div className={cn('space-y-3', preview && 'line-clamp-3')}>
          {renderSummary(notes.summary, compact || preview)}
        </div>
        {preview && notes.bullets && notes.bullets.length > 0 ? (
          <p className="text-xs text-zinc-500">Open the audit page for the full next-session rules.</p>
        ) : null}
      </CardContent>
    </Card>
  );
}
